import time
n = str(input('Olá, \nSeja bem vindo!\nInforme o seu nome completo?\n ')).strip().upper()
time.sleep(0.5)
nome = n.split()
print('Oi {} {}, agora vamos analisar o seu nome.\n' .format(nome[0], (nome[len(nome)-1])))
time.sleep(2.2)
print('\n Analisando... \n')
time.sleep(3.0)
print('Primeiro nome : {}' .format(nome[0]))
print('Nome do meio: {} {}' .format(nome[1], (nome[len(nome)-2])))
print('Último nome: {}\n' .format(nome[len(nome)-1]))
time.sleep(2.5)
print('Seu nome em maiúscula é {}' . format(n.upper()))
print('Seu nome em minúsculo é {}'.format(n.lower()))
print('Seu nome tem ao todo {} letras\n ' .format(len(n)))
time.sleep(2.5)
print('\nAnalisando a vogal A do seu nome...\n')
time.sleep(3.5)
print(' A letra A aparece {} vezes .  ' .format(n.count('A')))
print(' A primeira letra A apareceu na posição {} ' .format(n.find('A')+1))
print(' A última letra A apareceu na posição {}\n ' .format(n.rfind('A')+1))
time.sleep(3.5)
print(' OBRIGADA, ATÉ MAIS.')